export { default as Icon } from './icon';
// export { default as IconAppStore } from './appstore';
// export { default as IconPlayStore } from './playstore';
export { default as IconBookmark } from './bookmark';
export { default as IconCode } from './code';
export { default as IconCodepen } from './codepen';
export { default as IconComputer } from './computer';
export { default as IconDesign } from './design';
export { default as IconError } from './error';
export { default as IconExternal } from './external';
export { default as IconFolder } from './folder';
export { default as IconFork } from './fork';
export { default as IconGitHub } from './github';
export { default as IconInstagram } from './instagram';
export { default as IconLinkedinFull } from './linkedin-full';
export { default as IconLinkedin } from './linkedin';
export { default as IconSites } from './sites';
export { default as IconStar } from './star';
export { default as IconTwitter } from './twitter';